--- 
abstract: Extract Text From Arbitrary File Types
author: 
  - Copyright 2005-2007 Daisuke Maki <daisuke@endeworks.jp>.
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: File-Extract
no_index: 
  directory: 
    - inc
    - t
requires: 
  CAM::PDF: 0
  Class::Data::Inheritable: 0
  Encode: 0
  File::MMagic::XS: 0
  HTML::TreeBuilder: 0
  IO::Scalar: 0
  IPC::Open2: 0
  MP3::Info: 0
  RTF::HTMLConverter: 0
  Spreadsheet::ParseExcel: 0
  UNIVERSAL::isa: 0
version: 0.07000
